export const mockUploads = [
  { id: 1, name: 'stmt_jan_2024.pdf', status: 'Complete', size: '1.2 MB' },
  { id: 2, name: 'chase_card_feb.pdf', status: 'Complete', size: '890 KB' },
  { id: 3, name: 'amex_mar_2024.png', status: 'Processing', size: '2.5 MB' },
  { id: 4, name: 'investment_portfolio.pdf', status: 'Error', size: '4.1 MB' },
];
export const statementCycleData = [
  { name: 'Jan', income: 4000, expenses: 2400 },
  { name: 'Feb', income: 3000, expenses: 1398 },
  { name: 'Mar', income: 2000, expenses: 9800 },
  { name: 'Apr', income: 2780, expenses: 3908 },
  { name: 'May', income: 1890, expenses: 4800 },
  { name: 'Jun', income: 2390, expenses: 3800 },
];
export const creditUtilizationData = [
  { name: 'Amex Gold', value: 400, limit: 2000, fill: '#000000' },
  { name: 'Chase Sapphire', value: 300, limit: 10000, fill: '#333333' },
  { name: 'Venture X', value: 650, limit: 15000, fill: '#666666' },
  { name: 'BofA Rewards', value: 200, limit: 5000, fill: '#999999' },
];
export const mockInsights = [
    { id: 1, type: 'Anomaly', text: 'Unusually high spending in "Dining" category this month: $1,250 vs. $450 average.' },
    { id: 2, type: 'Observation', text: 'Recurring subscription to "Streaming Service X" for $15.99 detected.' },
    { id: 3, type: 'Suggestion', text: 'Consider consolidating credit card debt to a lower-interest personal loan to save on interest payments.' },
    { id: 4, type: 'Anomaly', text: 'A large one-time payment of $5,000 to "Vanguard Investments" was detected.' },
];
export const mockAnalystReport = `
# Monthly Analyst Report: March 2024
## Executive Summary
This report provides a comprehensive analysis of your financial activity for March 2024. Overall spending increased by 15% compared to the previous month, primarily driven by the "Travel" and "Shopping" categories. While income remained stable, the savings rate decreased from 20% to 12%. Several anomalous transactions were identified and are detailed below.
## Key Metrics
- **Total Income:** $7,500.00
- **Total Expenses:** $6,600.00
- **Savings Rate:** 12%
- **Top Spending Category:** Travel ($2,300)
## AI-Generated Insights & Anomalies
- **Anomaly:** Unusually high spending in "Dining" category this month: $1,250 vs. $450 average.
- **Observation:** Recurring subscription to "Streaming Service X" for $15.99 detected.
- **Suggestion:** Consider consolidating credit card debt to a lower-interest personal loan to save on interest payments.
- **Anomaly:** A large one-time payment of $5,000 to "Vanguard Investments" was detected.
## Recommendations
1.  **Review Travel Expenses:** Analyze the $2,300 in travel spending to identify potential areas for cost savings in future trips.
2.  **Set Category Budgets:** Implement spending alerts for categories like "Dining" to prevent overspending.
3.  **Optimize Subscriptions:** Review all recurring subscriptions to ensure they are still providing value.
*This report was automatically generated by Analyst Ledger.*
`;